In [28]:
from pandas import read_csv
from matplotlib import pyplot
from statsmodels.tsa.ar_model import AutoReg
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_absolute_percentage_error
from math import sqrt
import numpy as np

In [43]:
PATH_TO_TEST_TRAIN_DATA = 'Tangni/Data/'

#### define dataset
series1 = read_csv(PATH_TO_TEST_TRAIN_DATA + '1-3.csv', header=0, usecols=[0,1], index_col=0) 
data1 = series1.values

series2 = read_csv(PATH_TO_TEST_TRAIN_DATA + '2-12.csv', header=0, usecols=[0,1], index_col=0) 
data2 = series2.values

series3 = read_csv(PATH_TO_TEST_TRAIN_DATA + '3-6.csv', header=0, usecols=[0,1], index_col=0) 
data3 = series3.values

series4 = read_csv(PATH_TO_TEST_TRAIN_DATA + '4-15.csv', header=0, usecols=[0,1], index_col=0) 
data4 = series4.values

series5 = read_csv(PATH_TO_TEST_TRAIN_DATA + '5-15.csv', header=0, usecols=[0,1], index_col=0) 
data5 = series5.values

In [44]:


# train, test = X[:62], X[62:]
# # train autoregression
# model = AutoReg(train, lags=1)
# model_fit = model.fit()
# # print('Coefficients: %s' % model_fit.params)
# # make predictions
# trainpredictions = model_fit.predict(start=0, end=62, dynamic=False)
# predictions = model_fit.predict(start=len(train), end=len(train)+len(test)-1, dynamic=False)
# # for i in range(len(predictions)):
# # 	print('predicted=%f, expected=%f' % (predictions[i], test[i]))
# trainrmse = sqrt(mean_squared_error(train, trainpredictions))
# rmse = sqrt(mean_squared_error(test, predictions))
# print('Train RMSE: %.3f' % trainrmse)
# print('Test RMSE: %.3f' % rmse)
# # plot results
# pyplot.plot(test)
# pyplot.plot(predictions, color='red')
# pyplot.show()

In [45]:
def Autoregression(train,test,lags=1):
    # train autoregression
    model = AutoReg(train, lags=lags)
    model_fit = model.fit()
    # print('Coefficients: %s' % model_fit.params)
    # make predictions
    trainpredictions = model_fit.predict(start=0, end=62, dynamic=False)
    predictions = model_fit.predict(start=len(train), end=len(train)+len(test)-1, dynamic=False)
    # for i in range(len(predictions)):
    # 	print('predicted=%f, expected=%f' % (predictions[i], test[i]))
    
    trainrmse = sqrt(mean_squared_error(train[lags-1:], trainpredictions))
    rmse = sqrt(mean_squared_error(test, predictions))
    return trainrmse, rmse

In [46]:

Data = [[data1[:62],data1[62:]],[data2[:62],data2[62:]],[data3[:62],data3[62:]],[data4[:62],data4[62:]],[data5[:62],data5[62:]]]


In [6]:
Autoregression(Data[0][0],Data[0][1],lags=2)

(0.2796860838869437, 1.0900710807333311)

In [10]:
RMSE = []
RMSET = []
RMSETT = []
for i in range(1,20):
    T1, TT1 = Autoregression(Data[0][0],Data[0][1],lags=i)
    T2, TT2 = Autoregression(Data[1][0],Data[1][1],lags=i)
    T3, TT3 = Autoregression(Data[2][0],Data[2][1],lags=i)
    T4, TT4 = Autoregression(Data[3][0],Data[3][1],lags=i)
    T5, TT5 = Autoregression(Data[4][0],Data[4][1],lags=i)
    
    RMSET.append([T1,T2,T3,T4,T5])
    RMSETT.append([TT1, TT2,TT3,TT4,TT5])
    AvgT =(T1+T2+T3+T4+T5)/5
    AvgTT =(TT1+TT2+TT3+TT4+TT5)/5
    
    RMSE.append([i,AvgT,AvgTT])

In [11]:
RMSE

[[1, 0.1493113264821814, 0.7268855060380013],
 [2, 0.16157089091753946, 0.8124232187746887],
 [3, 0.1877635408509189, 0.7330678610719564],
 [4, 0.2201636092144681, 0.6966416731875963],
 [5, 0.17249254332282743, 0.7159791436130756],
 [6, 0.17623533948200484, 0.6734616614030886],
 [7, 0.2045058368893832, 0.7353175815770305],
 [8, 0.20642452069818212, 0.7583451931671503],
 [9, 0.21162408023288898, 0.7438989138142131],
 [10, 0.21631867680833028, 0.7417923319847519],
 [11, 0.22330553699526487, 0.7911420971816914],
 [12, 0.2282905833107672, 0.790239202518519],
 [13, 0.23459990196417868, 0.8145693689512428],
 [14, 0.254774728200047, 0.89042970500293],
 [15, 0.26100108909715786, 0.9080770640596022],
 [16, 0.2320250370565816, 0.7570480878131269],
 [17, 0.2349898224968201, 0.6868808279677252],
 [18, 0.2434947207884465, 0.7469503668483772],
 [19, 0.2500279960047059, 0.7698705935439731]]

In [32]:
def Autoregression2(train,test,lags=1):
    # train autoregression
    model = AutoReg(train, lags=lags)
    model_fit = model.fit()
    # print('Coefficients: %s' % model_fit.params)
    # make predictions
    trainpredictions = model_fit.predict(start=0, end=62, dynamic=False)
    predictions = model_fit.predict(start=len(train), end=len(train)+len(test)-1, dynamic=False)
    # for i in range(len(predictions)):
    # 	print('predicted=%f, expected=%f' % (predictions[i], test[i]))
    
    RMSE  = sqrt(mean_squared_error(train[lags-1:], trainpredictions))
    RMSET = sqrt(mean_squared_error(test, predictions))
    MAE   = mean_absolute_error(train[lags-1:], trainpredictions)
    MAET  = mean_absolute_error(test, predictions)
    MAPE  = mean_absolute_percentage_error(train[lags-1:], trainpredictions)
    MAPET = mean_absolute_percentage_error(test, predictions)
    return np.array([RMSE, RMSET, MAE, MAET, MAPE, MAPET])

In [47]:
E1 = Autoregression2(Data[0][0],Data[0][1],lags=1)
E2 = Autoregression2(Data[1][0],Data[1][1],lags=1)
E3 = Autoregression2(Data[2][0],Data[2][1],lags=1)
E4 = Autoregression2(Data[3][0],Data[3][1],lags=1)
E5 = Autoregression2(Data[4][0],Data[4][1],lags=1)

In [67]:
print(E1)

[0.2207051  0.74416719 0.19701446 0.69395123 0.16277481 0.12544245]


In [59]:
print(E2)

[1.03371086e-01 1.19894929e-06 1.32526927e-02 1.19894616e-06
 7.98456293e-03 4.87195039e-07]


In [60]:
print(E3)

[0.0159074  1.55618721 0.00756198 0.74927892 4.81394576 0.69972076]


In [61]:
print(E4)

[0.17157356 0.09553332 0.05296465 0.07169231 4.0772916  0.02143506]


In [62]:
print(E5)

[0.23499949 1.23853862 0.20586721 1.09031117 1.1204109  1.01615631]


In [63]:
M=E1+E2+E3+E4+E5

In [64]:
M=M/5

In [65]:
print(M)

[0.14931133 0.72688551 0.0953322  0.52104697 2.03648153 0.37255101]


In [72]:
1.03371086e-01

0.103371086

In [74]:
print(E1[0],E2[0],E3[0],E4[0],E5[0])
print(E1[2],E2[2],E3[2],E4[2],E5[2])
print(E1[4],E2[4],E3[4],E4[4],E5[4])
print(E1[1],E2[1],E3[1],E4[1],E5[1])
print(E1[3],E2[3],E3[3],E4[3],E5[3])
print(E1[5],E2[5],E3[5],E4[5],E5[5])

0.2207050969604075 0.1033710860415063 0.01590739711873246 0.1715735617638277 0.23499949052643299
0.1970144623403585 0.013252692680932576 0.007561975857429869 0.05296464949424257 0.20586720953421547
0.16277480829959035 0.007984562931081839 4.813945759443575 4.077291601587211 1.1204108997371938
0.7441671855513384 1.1989492891633446e-06 1.5561872072268865 0.0955333213402928 1.2385386171221997
0.6939512284335083 1.1989461569106297e-06 0.7492789225622091 0.07169230894639597 1.0903111717614775
0.12544244752443565 4.871950392726701e-07 0.699720760359003 0.0214350623924806 1.0161563080910059
